### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by declanosullivan** [declanosullivan/ADHD-Superheros#3]
Traceback (most recent call last):
  File "/app/run.py", line 354, in <module>
    main_menu()
  File "/app/run.py", line 64, in main_menu
    main()
  File "/app/run.py", line 346, in main
    calc_weekly_avg()
  File "/app/run.py", line 218, in calc_weekly_avg
    weekly_avg_num = (wkdone / wktotal)
ZeroDivisionError: division by zero

**Comment by declanosullivan** [comment]
A possible solution:

- If wktotal= 0, print "no priorites for the last 7 days" and move to next function

This should also be applied to calc_monthly_avg function

**Comment by declanosullivan** [comment]
Addin if/else statement for when wktotal or mthtotal are 0 resolved the issue.
