### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by declanosullivan** [declanosullivan/ADHD-Superheros#4]
Traceback (most recent call last):
  File "run.py", line 503, in <module>
    main_menu()
  File "run.py", line 64, in main_menu
    main()
  File "run.py", line 493, in main
    get_advice_data()
  File "run.py", line 293, in get_advice_data
    ADVICE_NAME = random_row[0]
IndexError: list index out of range

**Comment by declanosullivan** [comment]
Fixed by closing spreadsheet or typing in same range python is trying to access
